commands:

  urbanisme:

    description: Commission urbaine MoodCraft

    usage: /urbanisme

    aliases:
      - tgrade
      - commission
      - urbain
      - mairie

  topville:

    description: Classement national des villes

    usage: /topville

  projet:

    description: Ouvrir les projets municipaux

    usage: /projet

    aliases:
      - projets
      - tprojet
      - tprojets

  vprojet:

    description: Votes citoyens des projets

    usage: /vprojet

    aliases:
      - vprojets