name: MoodTownGrade

version: 1.0

main: fr.moodcraft.tgrade.Main

api-version: '1.21'

author: MoodCraft

depend:
  - Towny

commands:

  urbanisme:
    description: Commission urbaine MoodCraft
    usage: /urbanisme
    aliases:
      - tgrade
      - commission
      - urbain
      - mairie
      - projet
      - projets
      - tprojet
      - tprojets
      - vprojet
      - vprojets

  topville:
    description: Classement national des villes
    usage: /topville

  vprojetsreset:
    description: Reset national des projets urbains
    permission: moodtowngrade.staff

permissions:

  moodtowngrade.staff:
    default: op

  moodtowngrade.admin:
    default: op