name: Build Plugin

on:
  push:
    branches:
      - main

  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      #
      # 📥 CLONE
      #

      - name: Checkout repository
        uses: actions/checkout@v4

      #
      # ☕ JAVA 21
      #

      - name: Setup Java
        uses: actions/setup-java@v4

        with:
          distribution: temurin
          java-version: 21

      #
      # 📦 CACHE MAVEN
      #

      - name: Cache Maven
        uses: actions/cache@v4

        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      #
      # 🔨 BUILD
      #

      - name: Build with Maven
        run: mvn clean package

      #
      # 📤 UPLOAD JAR
      #

      - name: Upload artifact
        uses: actions/upload-artifact@v4

        with:
          name: MoodTownGrade

          path: target/*.jar